FROM gradle:7.2-jdk11 as build
# COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /usr/local/tomcat
COPY . .
RUN gradle build -x test --no-daemon 
# RUN gradle build 


FROM tomcat:9.0

COPY ./build/libs/class_schedule.war /usr/local/tomcat/webapps/

EXPOSE 8080

CMD ["catalina.sh", "run"]
